### PR TITLE
Add nix flake for building on nixos

### PR DESCRIPTION
**Pull request by pyrotelekinetic**

### CODE REVIEW

**Comment by olus2000** [comment]
No description provided...

**Comment by olus2000** [comment]
For the sake of bookkeeping I copy from discord:
> It would be nice to have even a short explanation of each supported build method, so if you can [write one for nix] then please do

**Comment by pyrotelekinetic** [comment]
Let me know if you want that section moved somewhere else in the readme

**Comment by olus2000** [comment]
A bit, but I'll do it myself

**Pull request merged**
